<?php

namespace Gestion\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commande_payementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commande_payementRepository extends EntityRepository
{
}
