<?php

namespace Gestion\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContacteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContacteRepository extends EntityRepository
{
}
