<?php

namespace Gestion\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageoffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
class ImageoffreRepository extends EntityRepository
{
    
      public function findbyid($id)
    {
 
 
       $qb = $this->createQueryBuilder('e')
                ->join('GestionAdminBundle:offre', 'h', 'WITH', 'e.offre='.$id)
               ->where('h.id='.$id);
              
          return $qb->getQuery()->getResult();
    
    }
}
