<?php

namespace Gestion\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrixpayementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixpayementRepository extends EntityRepository
{
}
